defaults:
  - data: predict
  - model: drugcell
  - trainer: predict
  - logger: base
  - _self_

trainer:
  save_dir: ../../../data/rlipp/feature/

data:
  test:
    path: ../../../data/cross_valid/drugcell_split_1.txt
    batch_size: 1024
