defaults:
  - logger: base
  - _self_

onto: ../../../data/drugcell_ont.txt
terms: ../../../data/go_text/vnn.txt
data: ../../../data/cross_valid/drugcell_split_1.txt
pred: ../../../data/rlipp/feature/Final_root.txt
gene2id: ../../../data/gene2ind.txt
cell2id: ../../../data/cell2ind.txt
feature_dir: ../../../data/rlipp/feature/
cpu_num: 8
hid_num: 6
index_flag: Cell
index_num: null
gene_output: null
rlipp_output: ./rlipp.txt
