test0='../../../data/cross_valid/drugcell_split_1.txt'
test1='../../../data/cross_valid/drugcell_split_2.txt'
test2='../../../data/cross_valid/drugcell_split_3.txt'
test3='../../../data/cross_valid/drugcell_split_4.txt'
test4='../../../data/cross_valid/drugcell_split_5.txt'
output0='hydra.run.dir=./outputs/base_cross_validation/0_mul_final/'
output1='hydra.run.dir=./outputs/base_cross_validation/0_large/'
output2='hydra.run.dir=./outputs/base_cross_validation/2/'
output3='hydra.run.dir=./outputs/base_cross_validation/3/'
output4='hydra.run.dir=./outputs/base_cross_validation/4/'
save0='trainer.save_dir=../../../ckpt/large/cv0'
save1='trainer.save_dir=../../../ckpt/baseline/cv0_large'
save2='trainer.save_dir=../../../ckpt/baseline/cv2'
save3='trainer.save_dir=../../../ckpt/baseline/cv3'
save4='trainer.save_dir=../../../ckpt/baseline/cv4'
ckpt1='trainer.ckpt=../../../ckpt/baseline/cv0_large/ckpt-epoch10.pt'
c0='trainer.device=cuda:0'
c1='trainer.device=cuda:1'
notest='data.test=null'

nohup python src/train.py +kay=cross ~data.train.path.0 ~data.val.path.0 $save0 $c0 $output0 > outputs/base_cross_validation/0_mul-final.txt &
