# @package _global_
defaults:
  - override /data: cross_valid
  - _self_

data:
  test:
    path: null
    batch_size: 3072
  train:
    batch_size: 3072
  val:
    batch_size: 256

trainer:
  save_dir: null
  lr: 2e-2
  scheduler: Plateau
