# @package _global_
defaults:
  - override /data: cross_valid
  - override /model: dc-text
  - _self_

model:
  vnn:
    text_terms: ../../../data/go_text/vnn_small.txt
    onto: ../../../data/drugcell_ont_small.txt

data:
  test: null
  train:
    batch_size: 2048
    label: True
  val:
    batch_size: 1024
    label: True

trainer:
  epoch: 100
  ckpt: ../../../ckpt/text/dc_text_v2.pt
  save_dir: ../../../ckpt
  lr: 2e-2
  scheduler: Plateau
  epoch_criterion: spearman
  save_period: 10
