# @package _global_
defaults:
  - override /data: cross_valid
  - _self_

model:
  criterion: 
    name: text
    lambda_r: 0.0
    lambda_t: 0.02
  vnn:
    text_dim: 768
    text_terms: ../../../data/go_text/vnn_non-zero.txt

data:
  test: null
  train:
    batch_size: 2048
    label: True
  val:
    batch_size: 1024
    label: True

trainer:
  epoch: 100
  ckpt: ../../../ckpt/text/dc_text_v2.pt
  save_dir: ../../../ckpt
  lr: 2e-2
  scheduler: Plateau
  epoch_criterion: spearman
