# @package _global_
defaults:
  - override /data: cross_valid
  - _self_

model:
  criterion: 
    name: text
    lambda_r: 0.0
    lambda_t: 0.02
  vnn:
    text_dim: 768

data:
  test:
    path: null
    batch_size: 1024
    label: True
  train:
    batch_size: 3072
    label: True
  val:
    batch_size: 1024
    label: True

trainer:
  ckpt: ../../../ckpt/text/dc_text_v1.pt
  save_dir: ../../../ckpt
  lr: 2e-2
  scheduler: Plateau
  epoch_criterion: spearman
